### ISSUE TITLE
Zpětná vazba životopis

### ISSUE THREAD

**Issue by IxAriela** [PetraSchneider/Petra_Schneiderova_ukol1#1]
Ahoj,

docela minimalistický životopis, takový trošku tabulkový :-D což je ale naprosto v pohodě :) chválím použití mailto u e-mailu.

Našla jsem tam ale dost chyb, nejvíce v HTML části (tam ti chybí i věci, které byly v zadání jako povinné), plus se to html docela špatně čte, zkus to trošku lépe naformátovat. Po opravě a hlavně doplnění věcí ze zadání se na to mrknu ještě jednou a je možné, že ti ještě něco k opravě dám.

- [x] Prosím, podívej se ještě jednou na zadání a doplň si chybějící části
- [x] chybí ti začátek body
- [x] H1 je hlavní nadpis a ten bývá na stránce pouze jeden
- [x] img má povinný alternativní popis, kdyby se obrázek nezobrazil (alt="popis"), prosím, doplň jej
- [x] cm se na webu vůbec nepoužívají (nikdy by mě nenapadlo, že budou fungovat :-D), používej prosím i pro obrázky px nebo (r)emy

**Comment by PetraSchneider** [comment]
Ahoj, opravila jsem chyby snad se v tom dá již lépe orientovat.
Děkuji

**Comment by IxAriela** [comment]
Ahoj, super, mnohem lepší, ale pořád tam nějak nevidím ten začátek body...

**Comment by PetraSchneider** [comment]
Ahoj, nevím co myslýš tím začátek body?
